### ISSUE TITLE
Virtual Environment?

### ISSUE THREAD

**Issue by benfwalla** [digitros/nextjs-fastapi#14]
What if I want to make a virtual environment to support my Python build? Where should I put `/venv` in the repo? I'm guessing the root, as that is where `requirements.txt` is, but that's just my guess. Would love to know if there is a best practice here.

**Comment by MomchilovP** [comment]
you can create a virtual environment in the root directory and it will work fine

**Comment by MomchilovP** [comment]
> What if I want to make a virtual environment to support my Python build? Where should I put `/venv` in the repo? I'm guessing the root, as that is where `requirements.txt` is, but that's just my guess. Would love to know if there is a best practice here.

you can create a virtual environment in the root directory and it will work fine
