### ISSUE TITLE
Swagger UI

### ISSUE THREAD

**Issue by riziles** [digitros/nextjs-fastapi#3]
Thanks for the great template! I've been playing around with trying to get the Swagger UI to work. I found that if I make the following tweaks to `next.config.js` then I can see them in dev. Haven't tried deploying to Vercel yet. Curious to know if you see any issues with this approach?

```javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
  rewrites: async () => {
    return [
      {
        source: "/api/:path*",
        destination:
          process.env.NODE_ENV === "development"
            ? "http://127.0.0.1:8000/api/:path*"
            : "/api/",
      },
      {
        source: "/docs",
        destination:
          process.env.NODE_ENV === "development"
            ? "http://127.0.0.1:8000/docs"
            : "/api/docs",
      },
      {
        source: "/openapi.json",
        destination:
          process.env.NODE_ENV === "development"
            ? "http://127.0.0.1:8000/openapi.json"
            : "/api/openapi.json",
      },
    ];
  },
};

module.exports = nextConfig;
```

**Comment by digitros** [comment]
> Thanks for the great template! I've been playing around with trying to get the Swagger UI to work. I found that if I make the following tweaks to `next.config.js` then I can see them in dev. Haven't tried deploying to Vercel yet. Curious to know if you see any issues with this approach?
> 
> 
> 
> ```javascript
> 
> /** @type {import('next').NextConfig} */
> 
> const nextConfig = {
> 
>   rewrites: async () => {
> 
>     return [
> 
>       {
> 
>         source: "/api/:path*",
> 
>         destination:
> 
>           process.env.NODE_ENV === "development"
> 
>             ? "http://127.0.0.1:8000/api/:path*"
> 
>             : "/api/",
> 
>       },
> 
>       {
> 
>         source: "/docs",
> 
>         destination:
> 
>           process.env.NODE_ENV === "development"
> 
>             ? "http://127.0.0.1:8000/docs"
> 
>             : "/api/docs",
> 
>       },
> 
>       {
> 
>         source: "/openapi.json",
> 
>         destination:
> 
>           process.env.NODE_ENV === "development"
> 
>             ? "http://127.0.0.1:8000/openapi.json"
> 
>             : "/api/openapi.json",
> 
>       },
> 
>     ];
> 
>   },
> 
> };
> 
> 
> 
> module.exports = nextConfig;
> 
> ```

Looks really great. I don't see any problem for this.
