### ISSUE TITLE
Refreshing failing

### ISSUE THREAD

**Issue by ThisIsRahmat** [digitros/nextjs-fastapi#7]
I have been using this template for a personal project but unfortunately I have noticed that when I make any changes to my nextjs files the change isn't shown until I 'ctrl + c' on my terminal. 

I believe this should be a quick fix and an improvement that would improve the experience of using this template.

**Comment by DeveloperRyan** [comment]
This is an issue caused on windows in the latest version of Uvicorn. Try using `uvicorn[standard]==0.21.1`.
